**1. Dot Product vs. Matrix Multiplication (`np.dot` vs. `np.matmul`)**

While `np.dot` and `np.matmul` behave similarly for 2D arrays, their underlying intent and behavior with higher-dimensional tensors (like image batches or word embeddings) differ.

Use `np.dot` for traditional vector-vector inner products.

Use `np.matmul` (or the `@` operator) for standard matrix-matrix multiplication, as it natively supports batch broadcasting.

In [2]:
import numpy as np

# 1. Vector Dot Product (1D Arrays)
# Measures similarity or projection. Result is a scalar.
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])
dot_product = np.dot(v1, v2)  # (1*4) + (2*5) + (3*6)
print("1. Vector Dot Product:", dot_product)

# 2. Matrix Multiplication (2D Tensors)
# Transforms a space. Crucial rule: Inner dimensions must match!
# A: (2 × 3) — e.g., 2 data samples, 3 features
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

# B: (3 × 2) — e.g., 3 feature weights across 2 output classes
B = np.array([
    [7, 8],
    [9, 1],
    [2, 3]
])

# Preferred production syntax: using the @ operator
matrix_mul = A @ B  # Resulting shape: (2 × 2)
print("\n2. Matrix Multiplication (A @ B):\n", matrix_mul)

1. Vector Dot Product: 32

2. Matrix Multiplication (A @ B):
 [[31 19]
 [85 55]]


**2. Transposition & Matrix Inversion**

Transposition flips an array over its diagonal, switching row and column metadata. 

Inversion represents the matrix equivalent of division ($A^{-1}$), which is critical for finding closed-form analytical solutions in classical models like Ordinary Least Squares (OLS) linear regression.

In [3]:
# Create a square feature matrix
M = np.array([
    [1, 2],
    [3, 4]
], dtype=np.float32)

# 1. Transpose: Flips rows to columns
M_T = M.T  # alternative: np.transpose(M)
print("1. Transposed Matrix:\n", M_T)

# 2. Inverse: Computes M^-1 such that M @ M^-1 = Identity Matrix (I)
M_inv = np.linalg.inv(M)
print("\n2. Matrix Inverse:\n", M_inv)

# Verification check: Matrix multiplied by its inverse yields the Identity Matrix
identity_test = np.round(M @ M_inv)
print("\n3. Verification (M @ M_inv):\n", identity_test)

1. Transposed Matrix:
 [[1. 3.]
 [2. 4.]]

2. Matrix Inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]

3. Verification (M @ M_inv):
 [[1. 0.]
 [0. 1.]]


**3. Determinants and Eigen-Decomposition (`det`, `eig`)**

The determinant gives a scale of how much linear transformations scale areas/volumes. 

If $\det(A) = 0$, the matrix is singular and cannot be inverted.

Eigenvectors are directions along which a linear transformation only stretches, compresses, or flips the space—the scale of that change is the eigenvalue. 

This math forms the engine behind Principal Component Analysis (PCA) dimensionality reduction.

In [4]:
# Matrix representing a structural geometric transformation
A_geom = np.array([
    [4, 2],
    [1, 3]
], dtype=np.float32)

# 1. Compute Determinant
determinant = np.linalg.det(A_geom)
print(f"1. Matrix Determinant: {determinant:.4f}")

# 2. Compute Eigenvalues and Eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A_geom)

print("\n2. Eigenvalues (Scale Factors):", eigenvalues)
print("\n3. Eigenvectors (Direction Matrix):\n", eigenvectors)

1. Matrix Determinant: 10.0000

2. Eigenvalues (Scale Factors): [5. 2.]

3. Eigenvectors (Direction Matrix):
 [[ 0.8944272  -0.70710677]
 [ 0.4472136   0.70710677]]


**4. Solving a 3-Variable Linear Equation System**

Let's solve the following system of linear equations using matrix algebra:

$$2x + 1y + 1z = 8$$

$$1x + 3y + 2z = 13$$

$$1x + 0y + 1z = 3$$

We convert this system into the matrix equation $Ax = B$, where $A$ holds the feature coefficients, $B$ is the target output vector, and $x$ is our vector of unknown variables ($x, y, z$). We solve it analytically via $x = A^{-1}B$.

In [5]:
# 1. Encode the system variables as coefficient matrix A and target vector B
A = np.array([
    [2, 1, 1],
    [1, 3, 2],
    [1, 0, 1]
], dtype=np.float32)

B = np.array([8, 13, 3], dtype=np.float32)

# 2. Solve the equation system using NumPy's optimized lapack routine solver
# Note: np.linalg.solve(A, B) is numerically more stable than manually calculating inv(A) @ B
solution = np.linalg.solve(A, B)

print("--- System Solution ---")
print(f"x = {solution[0]:.4f}")
print(f"y = {solution[1]:.4f}")
print(f"z = {solution[2]:.4f}")

# 3. Double Check the output via reconstruction: A @ solution must equal B
print("\nVerification check (A @ solution):", np.allclose(A @ solution, B))

--- System Solution ---
x = 2.0000
y = 3.0000
z = 1.0000

Verification check (A @ solution): True
